language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
matrix:
  allow_failures:
    - rust: nightly
    - os: osx
script:
  - cargo install --debug cargo-make
  - cargo make ci-flow
